name: 'dbt_training'
version: '1.0.0'
config-version: 2

profile: 'dbt_training'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" 
clean-targets: 
  - "target"
  - "dbt_packages"
  - "logs"

seeds:
  dbt_training:
    sale_dates:
      +column_types:
        sale_date: date
        name: varchar
        discount_percent: numeric(18,2)

vars:
  default_date: '9999-01-01'

on-run-start: 
  - "{{ audit_prep() }}"
  - "{{ audit_log('run_start') }}"
on-run-end: 
  - "{{ audit_log('run_end') }}"

models:
  dbt_training:
    +pre-hook:
      - "{{ log('THIS IS A PRE-HOOK') }}"
      - "{{ audit_log('model_start') }}"
    +post-hook:
      - "{{ log('THIS IS A POST-HOOK') }}"
      - "{{ audit_log('model_end') }}"
    staging:
      +materialized: view
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table