dbt_training:
  outputs:
    dev:
      account: yl45797.east-us-2.azure
      database: analytics_015
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: developer_015
      schema: dbt_szajec_dev
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_USER') }}"
      warehouse: developer_wh_015
    prod:
      account: yl45797.east-us-2.azure
      database: analytics_015
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: developer_015
      schema: dbt_szajec_prod
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_USER') }}"
      warehouse: developer_wh_015
  target: dev